In [1]:
import numpy as np

a = np.random.randn(5)

In [5]:
print(a)

[ 0.25447415 -1.72490064 -0.44935347 -0.63693326  0.73858557]


In [6]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[ 0.25447415 -1.72490064 -0.44935347 -0.63693326  0.73858557]


In [7]:
print(np.dot(a,a.T))

4.1931504703008935


In [8]:
a = np.random.randn(5,1)
print(a)

[[ 3.39913843]
 [-0.36755683]
 [-0.04618835]
 [-1.53578837]
 [ 0.72209823]]


In [9]:
print(a.T)

[[ 3.39913843 -0.36755683 -0.04618835 -1.53578837  0.72209823]]


In [10]:
print(np.dot(a,a.T))

[[ 1.15541420e+01 -1.24937656e+00 -1.57000584e-01 -5.22035725e+00
   2.45451185e+00]
 [-1.24937656e+00  1.35098026e-01  1.69768424e-02  5.64489509e-01
  -2.65412140e-01]
 [-1.57000584e-01  1.69768424e-02  2.13336337e-03  7.09355254e-02
  -3.33525234e-02]
 [-5.22035725e+00  5.64489509e-01  7.09355254e-02  2.35864591e+00
  -1.10899006e+00]
 [ 2.45451185e+00 -2.65412140e-01 -3.33525234e-02 -1.10899006e+00
   5.21425857e-01]]
