In [2]:
import numpy as np

In [4]:
a = np.random.randn(12288,150)

In [5]:
b = np.random.randn(150,45)

In [6]:
c = np.dot(a,b)

In [7]:
c.shape

(12288, 45)

In [9]:
a = np.random.randn(3,3)
print(a)

[[ 0.46168465  0.71568111  1.2749096 ]
 [-1.29515579 -0.50708332 -0.48803755]
 [-1.52353151 -0.05234375 -1.59178319]]


In [10]:
b = np.random.randn(3,1)
print(b)

[[ 1.48634473]
 [ 0.28885676]
 [-0.32986996]]


In [11]:
c = a * b
print(c)

[[ 0.68622254  1.06374884  1.89495516]
 [-0.3741145  -0.14647444 -0.14097294]
 [ 0.50256728  0.01726663  0.52508145]]
